thebadge/thebadge-dapp

package.json, pages/badge/type/create.tsx, pages/curator/register.tsx, pages/index.tsx, src/components/form/CheckBox.tsx, src/components/form/CustomForm.tsx, src/components/form/ImageInput.tsx, src/components/form/NumberField.tsx, src/components/form/TextArea.tsx, src/components/form/helpers/FormField.tsx, src/components/form/helpers/Label.tsx, src/components/form/helpers/customSchemas.ts, src/components/form/helpers/schemaToComponent.ts, src/components/form/helpers/validators.ts, src/theme/theme.ts, yarn.lock
Please include a summary of the changes and the link to the notion task. Please also include relevant motivation and context. List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes.
=> feat: Dynamic form working with bad design

pages/badge/type/create.tsx, src/components/form/ExpirationField.tsx, src/components/form/NumberField.tsx, src/components/form/TokenInput.tsx
Fix the Number field to accept a number of decimals as a config throw prop values, also this PR fixes the look and feel to keep it consistent with the TextFields
Go to the forms and use them :)
=> fix: number  and expiration field

i18n/translations.en.json, pages/_app.tsx, pages/badge/[typeId]/[ownerAddress].tsx, pages/badge/[typeId]/index.tsx, pages/badge/explorer.tsx, pages/badge/mint/[typeId].tsx, pages/badge/mint/index.tsx, pages/badge/type/[typeId].tsx, pages/badge/type/create.tsx, pages/creator/profile.tsx, pages/creator/register.tsx, pages/curator/profile.tsx, pages/curator/register.tsx, pages/index.tsx, src/components/form/ExpirationField.tsx, src/components/form/customForms/GridFormContainer.tsx, src/components/form/formWithSteps/FormWithSteps.tsx, src/components/helpers/GeneralError.tsx, src/pagePartials/badge/BadgeTypeMetadata.tsx, src/pagePartials/badge/mint/MintSteps.tsx, src/pagePartials/badge/useKlerosDepositPrice.tsx
Fix some minor things around the app
=> fix: General fixes

src/components/form/ExpirationField.tsx, src/components/form/FileInput.tsx, src/components/form/ImageInput.tsx, src/components/form/customForms/CustomForm.tsx, src/components/form/customForms/dataGridToComponents.ts, src/components/form/helpers/FormField.tsx, src/components/form/helpers/FormStatus.tsx, src/components/form/helpers/customSchemas.ts, src/pagePartials/badge/type/CreateSteps.tsx
Update the FileInput to match the designs on Figma, also I added some minor changes to the Form Layout to fit with the new file input style. On the other hand, I took the chance and updated the _Expiration_ form field to have a Checkbox where the creator can enable the expiration time. 
Go and create a BadgeType, there you will see the new changes
=> feat: Improves Badge Type creation form

package.json, pages/badge/curate.tsx, pages/badge/type/create.tsx, pages/profile/index.tsx, src/contracts/abis/KlerosBadgeTypeController.json, src/contracts/abis/TheBadge.json, src/contracts/contracts.ts, src/pagePartials/badge/curate/BadgeCuration.tsx, src/pagePartials/badge/curate/ChallengeModal.tsx, src/pagePartials/badge/curate/useBadgeCost.ts, src/pagePartials/profile/Profile.tsx, src/subgraph/queries/badge.ts, src/subgraph/queries/badgeType.ts, src/subgraph/queries/fragments.ts, src/subgraph/queries/user.ts, yarn.lock
This PR has the development to challenge a badge that is in challenge time.
=> feat: challenge working

pages/badge/mint/[typeId].tsx, pages/badge/type/create.tsx, pages/creator/register.tsx, src/components/buttons/txButton.tsx, src/hooks/useTransaction.tsx, src/pagePartials/badge/challenge/ChallengeModal.tsx, src/pagePartials/profile/myProfile/BadgesYouOwnList.tsx
Use the hook `useTransaction` on all the places where we were doing transactions, and also I added the state of the transaction inside the hook, so now we can show diff kinds of visual feedback based on that state.
=> feat: Add transaction states

i18n/translations.en.json, src/components/displayEvidence/DisplayAddress.tsx, src/components/displayEvidence/DisplayEvidenceField.tsx, src/components/helpers/Address.tsx, src/pagePartials/badge/curate/CurateModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx
Display the requester address and also use the Address comp to properly display address values. In addition there are some minor UI improvements
=> feat: Improve evidence modal

i18n/translations.en.json, pages/_app.tsx, src/components/layout/DefaultLayout.tsx, src/pagePartials/badge/curate/CurateModal.tsx
Add tooltip when owner try to challenge they own badge, also a quick fix to the footer appearing before everything
=> fix: Add tooltip when owner try to challenge they own badge

i18n/translations.en.json, pages/badge/curate.tsx, pages/badge/explorer.tsx, src/pagePartials/profile/created/BadgesCreatedSection.tsx
- Add some nice animations on the explorer / curate and creator profile badge
- Fix some tech debt of translations
=> feat: UI pollishing

package.json, pages/badge/curate.tsx, pages/badge/explorer.tsx, src/components/common/MiniBadgePreviewContainer.tsx, src/components/form/formWithSteps/FormWithSteps.tsx, src/components/header/Header.tsx, src/pagePartials/badge/type/CreateSteps.tsx, src/pagePartials/profile/created/BadgesCreatedSection.tsx, src/subgraph/queries/badgeType.ts, yarn.lock
Improves on the Creation Form
Update UI-lib version
Filter the first 5 badge types
Remove the beta logo for now
=> feat: Improves on the Creation Form

package.json, src/components/utils/emptyBadges.tsx, src/pagePartials/home/BadgesInReviewSwiper.tsx, src/pagePartials/home/SectionBoxes.tsx, src/pagePartials/profile/myProfile/NearToExpireList.tsx, src/pagePartials/profile/myProfile/PendingList.tsx, yarn.lock
=> feat: Add empty badges instead of placeholders

pages/badge/mint/[modelId].tsx, pages/badge/model/create.tsx, pages/creator/register.tsx, src/components/form/AvatarInput.tsx, src/components/header/UserDropdown.tsx, src/pagePartials/badge/type/CreateSteps.tsx, src/pagePartials/creator/register/RegistrationInfoPreview.tsx, src/pagePartials/creator/register/RegistrationSteps.tsx, src/utils/badges/createBadgeModelHelpers.ts
Move hard business logic to helpers functions and letting those helpers ready to work with more advance configurations
=> fix: Refactor to improve badge model creation logic

i18n/translations.en.json, package.json, src/hooks/useDate.tsx, src/pagePartials/badge/BadgeModelPreview.tsx, src/pagePartials/badge/mint/MintSteps.tsx, src/pagePartials/badge/type/CreateSteps.tsx, src/pagePartials/creator/register/RegistrationSteps.tsx, src/pagePartials/home/BadgesInReviewSwiper.tsx, src/pagePartials/profile/myProfile/PendingList.tsx, src/subgraph/queries/badge.ts, src/subgraph/queries/fragments/badge.ts, yarn.lock
Merge changes made by @ramabit on Staging into Develop
=> feat: Update library

i18n/translations.en.json, pages/_app.tsx, src/components/layout/DefaultLayout.tsx, src/hooks/subgraph/useSubGraphStatus.tsx, src/pagePartials/errors/displays/OutOfService.tsx, src/pagePartials/errors/preventActionIfOutOfService.tsx
First implementation of the OOS component, we need to improve the designs and add more health checks if we need. Also will be cool to keep adding more error codes, in case some users face it and want to report it.
- Pull the branch
- Change the SG Url
- Run it
=> feat: Add out of service with status checks on SG

pages/badge/mint/[modelId].tsx, src/components/displayEvidence/DisplayEvidenceField.tsx, src/components/displayEvidence/DisplayImage.tsx, src/components/form/FileInput.tsx, src/components/form/helpers/customSchemas.ts, src/components/form/helpers/validators.ts, src/hooks/subgraph/useIsBadgeOwner.tsx, src/pagePartials/badge/curate/CurateModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx, src/pagePartials/badge/explorer/BadgeEvidenceInfoPreview.tsx, src/pagePartials/errors/requiredNotHaveBadge.tsx, src/utils/badges/mintHelpers.ts
Change shape of Evidence Schema
Add helper function to create object value as kleros want it
Fix Evidence Displayer to show evidence as should be 
Fix useIsBadgeOwner.tsx when the wallet is not connected 
Fix FileInput on ChallengeModal.tsx
=> fix: Change shape of Evidence Schema

.github/workflows/nextjs_bundle_analysis.yml, package.json, src/components/form/FileInput.tsx, src/hooks/kleros/useChallengeBaseDeposits.ts, src/hooks/kleros/useTCRContractInstance.ts, src/pagePartials/badge/GetBadgeTypeReviewDueDate.tsx, src/pagePartials/badge/curate/CurateModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeCost.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx, src/subgraph/queries/badge.ts, src/theme/global.css, src/utils/badges/challengeBadgesHelpers.ts, src/utils/dateUtils.ts, yarn.lock
=> fix: Trigger challenge

src/components/header/ActionButtons.tsx, src/components/header/Header.tsx, src/components/header/UserDropdown.tsx, src/pagePartials/badge/BadgeModelPreview.tsx, src/pagePartials/index/Head.tsx, src/pagePartials/profile/myProfile/BadgesYouOwnList.tsx, src/pagePartials/profile/myProfile/NearToExpireList.tsx, src/pagePartials/profile/myProfile/PendingList.tsx, src/subgraph/queries/badge.ts
Please include a summary of the changes and the link to the notion task. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> feat: Badge preview + Challenges

src/components/helpers/FilteredList.tsx, src/pagePartials/profile/Profile.tsx, src/pagePartials/profile/myProfile/BadgesYouOwnList.tsx
=> fix: profile filters

i18n/translations.en.json, pages/badge/curate.tsx, src/components/helpers/FilteredList.tsx, src/components/select/SearchField.tsx, src/constants/helpers.ts, src/pagePartials/profile/myProfile/BadgesYouOwnList.tsx, src/subgraph/queries/badge.ts, src/utils/badges/getHighlightColorByStatus.ts
Adding filter functionality to the curators page.
@FedeMadoery I've added a "clear" button in the `SearchField` as an endAdornment, could you give it styles, please?
=> feat: Curator - filters

i18n/translations.en.json, pages/badge/model/create.tsx, src/pagePartials/badge/mint/MintCost.tsx, src/pagePartials/badge/mint/MintSteps.tsx, src/utils/badges/createBadgeModelHelpers.ts, types/badges/BadgeMetadata.ts, types/utils.ts
Fix creator fee
Add Background to Model Metadata
Add TextContrast to metadata
=> fix: Mint value and some other minor issues

package.json, src/components/layout/Footer.tsx, yarn.lock
Update UI-Lib version and fix some imports that have changed
=> Update ui-lib and fix imports

i18n/translations.en.json, pages/badge/mint/[modelId].tsx, src/pagePartials/badge/curate/CurationCriteriaLink.tsx, src/pagePartials/badge/curate/challenge/ChallengeCost.tsx, src/pagePartials/badge/explorer/BadgeModelInfoPreview.tsx, src/pagePartials/badge/mint/MintCost.tsx, src/pagePartials/badge/mint/MintSteps.tsx
Fix some old texts referring to ´type' instead of ´model´
=> (Fix) - Old texts

src/subgraph/queries/fragments/user.ts, src/subgraph/queries/user.ts
Update queries to match new stats subgraph
=> feat: Update queries to match new subgraph

i18n/translations.en.json, src/components/form/TextField.tsx, src/pagePartials/badge/curate/CurateModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeCost.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx
Small fixes to have better spacing and better hierarchy
=> feat: Small fixes on curate and challenge modal

i18n/translations.en.json, src/components/common/TBModal.tsx, src/hooks/subgraph/useIsClaimable.tsx, src/pagePartials/badge/curate/CurateModal.tsx, src/pagePartials/badge/curate/CurationCriteriaLink.tsx, src/pagePartials/badge/curate/addEvidence/AddEvidenceModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeCost.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx, src/pagePartials/badge/curate/evidenceForm/EvidenceForm.tsx, src/pagePartials/badge/explorer/BadgeEvidenceInfoPreview.tsx, src/pagePartials/badge/mint/steps/preview/MintCost.tsx, src/pagePartials/badge/mint/steps/terms/HowItWorks.tsx, src/pagePartials/badge/preview/ChallengeStatus.tsx, src/pagePartials/profile/reviewing/BadgeEvidenceInfoPreview.tsx, src/providers/curateProvider.tsx, src/utils/dateUtils.ts
Removal modal rework
Add evidence modal new
Split EvidenceForm to a separate component to re-use it
Split TBModal to a separate component to re-use it
=> feat: Challenge modal rework

i18n/translations.en.json, src/components/helpers/FilteredList.tsx, src/components/helpers/TimeAgo.tsx, src/hooks/subgraph/useBadgeKlerosMetadata.tsx, src/pagePartials/badge/explorer/addons/ViewEvidenceButton.tsx, src/pagePartials/profile/reviewing/BadgeEvidenceInfoPreview.tsx, src/pagePartials/profile/reviewing/addons/DisputeDisplay.tsx, src/utils/dateUtils.ts
Add skeleton
Improve translations
=> feat: Add pulling for dispute id on profile

src/components/form/SeveritySelector/index.tsx, src/pagePartials/badge/explorer/BadgeRequesterPreview.tsx
Fix build issues on development
=> fix: conflicts with staging

package.json, yarn.lock
=> chore: Update ui-lib version

src/components/form/SeveritySelector/index.tsx, src/contracts/abis/TheBadge.json, src/hooks/theBadge/useIsUserVerified.ts, src/pagePartials/badge/explorer/BadgeRequesterPreview.tsx, src/pagePartials/badge/explorer/addons/BadgeRequesterPreview.tsx, src/pagePartials/badge/explorer/addons/CreatorInfoSmallPreview.tsx, src/pagePartials/badge/preview/BadgeOwnerPreview.tsx, src/pagePartials/profile/userInfo/InfoPreview.tsx
Adds useIsUserVerified() and uses it to check the user validation status on the SC
=> feat: Adds useIsUserVerified hook

src/pagePartials/badge/curate/challenge/ChallengeModal.tsx, src/pagePartials/profile/reviewing/BadgesIAmReviewingSection.tsx, src/subgraph/queries/badgeKlerosMetaData.ts, src/utils/badges/challengeBadgesHelpers.ts
=> feat: Add logic to do long-pulling on badges challenged

src/providers/themeProvider.tsx, src/theme/theme.ts
Improve tooltip reducing the line-height and setting diff background color on theme modes
=> feat: Fix tooltip line-height using theme components prop

src/hooks/theBadge/useIsUserVerified.ts, src/pagePartials/profile/userInfo/InfoPreview.tsx
Fix bug on useIsUserVerified using index instead of userAddress
=> fix: useIsUserVerified hook

i18n/translations.en.json, src/providers/web3ConnectionProvider.tsx
Update the logic that we use to update the We3Auth name to Social Login to allow the addition of more wallets
Remove svelte classes to prevent future errors
=> chore: Update logic on SocialLogin wallet

i18n/translations.en.json, src/pagePartials/badge/preview/BadgeOwnerPreview.tsx
Minor issues on text inside the badge/preview view
=> fix: text issues on badge/preview

i18n/translations.en.json, src/components/form/formFields/SeveritySelector/AdvanceView.tsx, src/components/form/formFields/SeveritySelector/styled.tsx
Improve a little bit the look and feel. Move tooltips to translation files so they can be improved at any time.
=> feat: Improve rigurusness summary

i18n/translations.en.json, src/components/header/UserDropdown.tsx, src/hooks/nextjs/useStatisticsVisibility.tsx, src/hooks/subgraph/useCreatorStatistics.tsx, src/hooks/subgraph/useCuratorStatistics.tsx, src/hooks/subgraph/useUserrStatistics.tsx, src/pagePartials/profile/Profile.tsx, src/pagePartials/profile/statistics/addons/StatisticRow.tsx, src/pagePartials/profile/statistics/addons/StatisticsHeader.tsx, src/pagePartials/profile/statistics/addons/StatisticsVisibilityToggle.tsx, src/pagePartials/profile/statistics/addons/styled.tsx, src/pagePartials/profile/statistics/creator/CreatorStatisticContent.tsx, src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx, src/pagePartials/profile/statistics/curator/CuratorStatisticContent.tsx, src/pagePartials/profile/statistics/curator/CuratorStatistics.tsx, src/pagePartials/profile/statistics/user/UserStatisticContent.tsx, src/pagePartials/profile/statistics/user/UserStatistics.tsx, src/subgraph/queries/statistics.ts, src/utils/numbers.ts
Add base elements for user statistics, and implements the creator, curator and user statistics.
=> feat: Creator/Curator/User statistics

src/subgraph/subgraph-endpoints.json
Setup usage of staging subgraphs for testnets
=> chore: Use staging subgraphs for testnets

.github/workflows/nextjs_bundle_analysis.yml, .nvmrc, package.json
=> chore: Use node 18 as min version

pages/badge/curate.tsx, src/pagePartials/badge/explorer/BadgeEvidenceInfoPreview.tsx, src/subgraph/queries/badge.ts
Update badgesUserCanReviewSmallSet to allow filter by Requested and other statuses
Hide review time when badges are approved
=> fix: Review time when badges are approved

src/pagePartials/badge/curate/evidenceForm/EvidenceForm.tsx
Fix file input onChange were it was using wrong property name, also add loading state on the button
=> fix: Challenge with file

i18n/translations.en.json, src/components/form/formFields/KlerosDynamicFormCreatorField/FormFieldCreator.tsx, src/pagePartials/profile/Profile.tsx, src/pagePartials/profile/statistics/creator/CreatorStatisticContent.tsx, src/pagePartials/profile/statistics/user/UserStatisticContent.tsx
1- There was an error in the profile after creating the first badge model.
2- Added translations
3- Fix access to created badges tab
=> fix: error on creator profile

i18n/translations.en.json
=> fix: typos

src/hooks/useActionObserver.tsx, src/pagePartials/profile/Profile.tsx, src/pagePartials/profile/myProfile/NearToExpireList.tsx, src/pagePartials/profile/myProfile/PendingList.tsx, src/pagePartials/profile/statistics/addons/StatisticsHeader.tsx, src/pagePartials/profile/statistics/creator/CreatorStatisticContent.tsx, src/pagePartials/profile/statistics/creator/CreatorStatistics.tsx, src/pagePartials/profile/statistics/curator/CuratorStatisticContent.tsx, src/pagePartials/profile/statistics/curator/CuratorStatistics.tsx, src/pagePartials/profile/statistics/user/UserStatisticContent.tsx, src/providers/ProfileProvider.tsx
Add a hook to help trigger actions from different contexts, the hook itself is quite simple, it just tries to emulate a trigger and an observer in the simplest way.
=> feat: Add profile statistics reload

src/subgraph/subgraph-endpoints.json
- Make use of `latest` graph version
=> feat: Update subgraph-endpoints.json

src/constants/common.ts
Update Kleros court script with new SG urls, to test it we need to create a new model and rise a challenge
=> fix: Update script hash

i18n/translations.en.json, src/pagePartials/home/statistics/ProtocolStatistics.tsx
- Improves the texts in the statistics of the home
=> feat: Improves stastics wording

i18n/translations.en.json, src/components/common/TBUserAvatar.tsx, src/components/helpers/Address.tsx, src/components/helpers/LinkWithTranslation.tsx, src/components/layout/Footer.tsx, src/components/toast/Toast.tsx, src/hooks/kleros/useChallengeCost.ts, src/hooks/kleros/useRemovalCost.ts, src/hooks/theBadge/useBadgeClaim.tsx, src/hooks/theBadge/useMintValue.ts, src/hooks/theBadge/useTBContract.tsx, src/hooks/useEnsLookup.tsx, src/pagePartials/badge/BadgeModelPreview.tsx, src/pagePartials/badge/curate/addEvidence/AddEvidenceModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx, src/pagePartials/badge/mint/MintCommunityBadgeModel.tsx, src/pagePartials/badge/mint/MintThirdPartyBadgeModel.tsx, src/pagePartials/badge/mint/steps/preview/MintCostThirdParty.tsx, src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/badge/preview/addons/BadgeTitle.tsx, src/subgraph/queries/fragments/badge.ts, types/relayedTx.ts, types/toast.ts
- Replaces ens name and avatar when the ens is registered for that user
- Several improvements on the badge profile
=> feat: Use ENS in profile

pages/badgeModel/[controllerType]/[modelId]/explorer/index.tsx, pages/badgeModel/explorer/index.tsx, pages/curate/index.tsx, src/components/common/BadgePreviewContainer.tsx, src/components/common/MiniBadgePreviewContainer.tsx, src/components/helpers/FilteredList/DesktopView.tsx, src/components/helpers/FilteredList/MobileView.tsx, src/components/helpers/FilteredList/SelectedItemPreviewWrapper.tsx, src/components/helpers/FilteredList/index.tsx, src/components/helpers/InViewPort.tsx, src/pagePartials/badge/explorer/BadgeModelInfoPreview.tsx, src/pagePartials/badge/explorer/addons/BadgeMintCost.tsx, src/pagePartials/badge/mint/steps/preview/MintCost.tsx, src/pagePartials/profile/created/BadgesCreatedSection.tsx, src/pagePartials/profile/myProfile/BadgesYouOwnList.tsx, src/pagePartials/profile/reviewing/BadgesIAmReviewingSection.tsx
First draft of mobile view for filtered list
=> chore: add filtered list mobile mode

src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/creator/register/schema/CreatorRegisterSchema.ts, src/pagePartials/profile/userInfo/InfoPreviewEdit.tsx, src/utils/navigation/generateUrl.ts, types/badges/Creator.ts
- Adds linkedin to the profile
- Also uses the LinkedIn URL to generate the linkedin URL
=> feat: Adds linkedin on the profile

pages/user/register/index.tsx, src/constants/common.ts, src/hooks/subgraph/useBadgeModelMaxAmount.tsx, src/hooks/subgraph/useBadgesUserCanReview.tsx, src/hooks/subgraph/useUserById.tsx, src/hooks/theBadge/useChainId.tsx, src/pagePartials/home/carousels/BadgeModelsList.tsx, src/pagePartials/home/carousels/BadgesInReviewSwiper.tsx, src/providers/web3ConnectionProvider.tsx
Use default network if the connected one is wrong, to prevent errores
=> fix: wrong network connection

pages/badge/[badgeId]/index.tsx, src/components/common/TBUserAvatar.tsx, src/components/common/TBUserInfoExpandablePreview.tsx, src/components/common/TBUserInfoSmallPreview.tsx, src/hooks/subgraph/useUserById.tsx, src/hooks/theBadge/useIsThirdPartyUser.ts, src/hooks/theBadge/useIsUserVerified.ts, src/pagePartials/badge/explorer/BadgeRequesterPreview.tsx, src/pagePartials/badge/explorer/addons/BadgeRequesterPreview.tsx, src/pagePartials/badge/explorer/addons/CreatorInfoSmallPreview.tsx, src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/badge/preview/BadgeOwnerPreview.tsx, src/pagePartials/profile/ProfileSelector.tsx, src/pagePartials/profile/myProfile/ManageBadges.tsx, src/pagePartials/profile/userInfo/InfoPreviewEdit.tsx, src/pagePartials/profile/userInfo/InfoPreviewRead.tsx
Move isVerified check into the TBAvatar to prevent long loading states when it's not needed
=> chore: Move isVerified check into avatar comp

src/config/web3.ts, src/hooks/etherjs/useEthersSigner.tsx
- Fixes the wallet connection when the user has no wallet connected
- Adds the rpc for gnosis chain
=> fix: useEthersSigner

i18n/translations.en.json, src/components/header/ActionButtons.tsx, src/pagePartials/profile/myProfile/ManageBadges.tsx
- Adds create button for third party users
=> feat: Add create buttons for third party

src/pagePartials/badge/model/CreateThirdPartyBadgeModel.tsx, src/pagePartials/badge/model/schema/CreateThirdPartyModelSchema.ts, src/pagePartials/badge/model/steps/thirdParty/strategy/BadgeModelStrategy.tsx
-  Remove administrators display
=> feat: Improves tp creation

pages/user/register/index.tsx, src/components/header/ActionButtons.tsx, src/pagePartials/profile/UserProfile.tsx
- Replace isCreator with isRegistered
=> fix: Replace isCreator with isRegistered

i18n/translations.en.json, src/hooks/theBadge/useBadgeModelTemplate.tsx, src/pagePartials/badge/mint/steps/StepHeader.tsx, src/pagePartials/badge/mint/steps/StepHeaderThirdParty.tsx, src/pagePartials/badge/mint/steps/dynamicForm/thirdParty/FormThirdParty.tsx, src/pagePartials/badge/mint/steps/preview/SubmitPreview.tsx, src/pagePartials/badge/mint/steps/preview/thirdParty/SubmitPreviewThirdParty.tsx, src/pagePartials/badge/mint/steps/terms/HowItWorksThirdParty.tsx, src/pagePartials/badge/model/CreateCommunityBadgeModel.tsx, src/pagePartials/badge/model/schema/CreateThirdPartyModelSchema.ts, src/pagePartials/badge/model/steps/community/StepHeaderCommunity.tsx, src/pagePartials/badge/model/steps/thirdParty/StepHeaderThirdParty.tsx, src/pagePartials/badge/model/steps/uiBasics/BadgeModelUIBasics.tsx, src/pagePartials/badge/model/utils.ts, src/pagePartials/badge/preview/BadgeThirdPartyPreviewGenerator.tsx, src/subgraph/subgraph.ts, src/utils/badges/createBadgeModelHelpers.ts, types/badges/BadgeModel.ts
- Updates the text according to third party
=> fix: Improve texts

pages/badgeModel/explorer/index.tsx, src/hooks/subgraph/useBadgeModelMaxAmount.tsx, src/subgraph/queries/badgeModel.ts
Show only community badges in main explorer
=> fix: Filter badge models per controller type

i18n/translations.en.json, src/hooks/subgraph/useIsClaimable.tsx, src/pagePartials/badge/explorer/ThirdPartyBadgeEvidenceInfoPreview.tsx
=> fix: Preview title

src/hooks/theBadge/useAddTokenIntoWallet.tsx, src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/badge/preview/DiplomaOwnedPreview.tsx
=> fix: addTokenIntoWallet

src/pagePartials/badge/mint/MintCommunityWithSteps.tsx, src/pagePartials/badge/mint/MintThirdPartyWithSteps.tsx, src/pagePartials/badge/model/CreateCommunityBadgeModelWithSteps.tsx, src/pagePartials/badge/model/CreateThirdPartyBadgeModelWithSteps.tsx
=> feat: Add notify when form validation fails

src/pagePartials/badge/model/steps/uiBasics/diploma/addons/FooterConfiguration.tsx, src/pagePartials/badge/model/utils.ts
=> fix: Add default name when creator data is missing

src/utils/navigation/generateUrl.ts
- Fixes how the certification url is generated
=> fix: Certification linkedin generation

src/hooks/etherjs/useEthersSigner.tsx, src/hooks/useEnsLookup.tsx, src/pagePartials/profile/userInfo/InfoPreviewEdit.tsx, src/utils/navigation/generateUrl.ts
=> chore: Update stagging with latest develop

i18n/translations.en.json, pages/badgeModel/create/[controllerType]/index.tsx, src/hooks/theBadge/useDecryptEmail.ts, src/pagePartials/badge/explorer/ThirdPartyBadgeEvidenceInfoPreview.tsx, src/pagePartials/badge/model/CreateCommunityBadgeModel.tsx, src/pagePartials/badge/model/CreateThirdPartyBadgeModel.tsx, src/utils/relayTx.ts
- Fixes the redirect of the third party profie
- Also adds the utility to decrypt the recipient email
=> feat: Redirect profile

pages/badge/[badgeId]/index.tsx, src/hooks/subgraph/useIsThirdPartyBadge.tsx, src/hooks/subgraph/useUserById.tsx, src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/badge/preview/DiplomaOwnedPreview.tsx, src/providers/web3ConnectionProvider.tsx
=> fix: Use contract from the URL to fetch the right data

i18n/translations.en.json, package.json, src/hooks/theBadge/useCreateModelFeeValue.ts, src/pagePartials/badge/claim/steps/StepsClaimThirdPartySucceed.tsx, src/pagePartials/badge/mint/MintThirdPartyWithSteps.tsx, src/pagePartials/badge/mint/steps/preview/thirdParty/MintCostThirdParty.tsx, src/pagePartials/badge/model/CreateCommunityBadgeModel.tsx, src/pagePartials/badge/model/CreateThirdPartyBadgeModel.tsx, src/pagePartials/badge/model/schema/CreateThirdPartyModelSchema.ts, src/pagePartials/badge/model/steps/thirdParty/strategy/BadgeModelStrategy.tsx, src/pagePartials/badge/model/steps/uiBasics/BadgeModelUIBasics.tsx, src/pagePartials/badge/model/steps/uiBasics/badge/BadgeConfiguration.tsx, src/utils/navigation/generateUrl.ts, yarn.lock
=> fix: create and mint badge tp

src/config/web3.ts, src/hooks/useEnsLookup.tsx
- Fixes polygon rpc url generation
=> fix: Fix polygon rpc url generation

src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/badge/preview/DiplomaOwnedPreview.tsx, src/pagePartials/badge/preview/addons/BadgeTitle.tsx, src/utils/navigation/generateUrl.ts
- Fix some urls not well formed
=> fix: Management tab

i18n/translations.en.json, src/components/common/TBUserInfoSmallPreview.tsx, src/hooks/subgraph/useBadgeKlerosMetadata.tsx, src/pagePartials/badge/curate/CurateModal.tsx, src/pagePartials/badge/curate/challenge/ChallengeModal.tsx, src/pagePartials/badge/explorer/BadgeEvidenceInfoPreview.tsx, src/pagePartials/badge/explorer/ThirdPartyBadgeEvidenceInfoPreview.tsx, src/pagePartials/badge/explorer/addons/BadgeIdDisplay.tsx, src/subgraph/queries/badge.ts, src/subgraph/queries/fragments/badgeKlerosMetaData.ts, src/theme/global.css
- Fixes bugs with the ui and the ids, check the commits
=> fix: Several ui fixes

next-env.d.ts, src/constants/backgrounds.ts, src/hooks/subgraph/utils.ts, src/hooks/useAvailableBackgrounds.tsx, src/pagePartials/badge/BadgeModelPreview.tsx, src/pagePartials/badge/MiniBadgeModelPreview.tsx, src/pagePartials/badge/mint/steps/preview/MintSucceed.tsx, src/pagePartials/badge/mint/steps/preview/SubmitPreview.tsx, src/pagePartials/badge/model/steps/uiBasics/badge/BadgeClassicCreationPreview.tsx, src/pagePartials/badge/model/steps/uiBasics/badge/addons/AdditionalConfiguration.tsx, src/pagePartials/badge/preview/BadgeView.tsx, src/utils/cache.ts
- Queries premium backgrounds from relayer
=> feat: Add premium backgrounds

i18n/translations.en.json, src/components/form/customForms/CustomForm.tsx, src/components/form/customForms/type.ts, src/hooks/theBadge/useSendMintNotificationEmail.ts, src/pagePartials/badge/mint/MintThirdPartyBadgeModel.tsx, src/pagePartials/badge/mint/schema/MintThirdPartySchema.ts, src/pagePartials/badge/mint/steps/dynamicForm/thirdParty/DynamicRequiredData.tsx, src/utils/relayTx.ts, types/relayedTx.ts
- Allows the tp creator to send a notification by email when it mints to an address
=> feat: Adds email notification in mint to address

package.json, src/hooks/theBadge/useBadgePreviewUrl.ts, src/hooks/useAvailableBackgrounds.tsx, src/pagePartials/badge/BadgeModelPreview.tsx, src/pagePartials/badge/MiniBadgeModelPreview.tsx, src/pagePartials/badge/claim/steps/StepsClaimThirdPartyPreview.tsx, src/pagePartials/badge/claim/steps/StepsClaimThirdPartySucceed.tsx, src/pagePartials/badge/mint/schema/MintThirdPartySchema.ts, src/pagePartials/badge/mint/steps/preview/MintSucceed.tsx, src/pagePartials/badge/mint/steps/preview/SubmitPreview.tsx, src/pagePartials/badge/mint/steps/preview/thirdParty/SubmitPreviewThirdParty.tsx, src/pagePartials/badge/model/schema/CreateCommunityModelSchema.ts, src/pagePartials/badge/model/steps/uiBasics/badge/BadgeClassicCreationPreview.tsx, src/pagePartials/badge/model/steps/uiBasics/badge/addons/AdditionalConfiguration.tsx, src/pagePartials/badge/model/steps/uiBasics/badge/addons/CustomFieldsConfiguration.tsx, src/pagePartials/badge/model/utils.ts, src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/badge/preview/BadgeView.tsx, src/pagePartials/badge/preview/DiplomaOwnedPreview.tsx, src/utils/badges/createBadgeModelHelpers.ts, src/utils/navigation/generateUrl.ts, types/badges/BadgeMetadata.ts, yarn.lock
=> feat: Add mini logo configs

src/components/helpers/FilteredList/DesktopView.tsx, src/components/helpers/FilteredList/index.tsx, src/pagePartials/badge/preview/BadgeView.tsx, src/pagePartials/badge/preview/DiplomaView.tsx, src/pagePartials/badge/preview/generators/BadgeItemGenerator.tsx, src/pagePartials/profile/myProfile/BadgesYouOwnList.tsx
Depends on #371 
- Replace model components with badge components on my badges owned list
=> feat: My badges profile improvements

i18n/translations.en.json, pages/curate/index.tsx, src/components/helpers/FilteredList/index.tsx, src/hooks/subgraph/useIsBadgeOwner.tsx, src/hooks/useListItemNavigation.tsx, src/pagePartials/badge/MiniBadgeModelPreview.tsx, src/pagePartials/badge/explorer/BadgeModelInfoPreview.tsx, src/pagePartials/badge/explorer/ThirdPartyBadgeModelInfoPreview.tsx, src/pagePartials/badge/model/CreateThirdPartyBadgeModel.tsx, src/pagePartials/badge/preview/BadgeView.tsx, src/pagePartials/errors/requiredNotHaveBadge.tsx, src/pagePartials/explorer/badgeModel/index.tsx, src/pagePartials/explorer/badges/index.tsx, src/pagePartials/profile/ManagementProfile.tsx, src/pagePartials/profile/ProfileSelector.tsx, src/pagePartials/profile/created/BadgesCreatedSection.tsx, src/pagePartials/profile/myProfile/ManageBadges.tsx, src/pagePartials/profile/reviewing/BadgesIAmReviewingSection.tsx, src/pagePartials/profile/userInfo/InfoAbout.tsx, src/pagePartials/profile/userInfo/InfoSocial.tsx, src/subgraph/queries/badgeModel.ts
- Allows the management tab for every user not only third parties
- Implements pause-unpause badges
=> feat: Implements management tab refactor

i18n/translations.en.json, pages/curate/index.tsx, src/components/helpers/FilteredList/index.tsx, src/hooks/subgraph/useIsBadgeOwner.tsx, src/hooks/useListItemNavigation.tsx, src/pagePartials/badge/MiniBadgeModelPreview.tsx, src/pagePartials/badge/explorer/BadgeModelInfoPreview.tsx, src/pagePartials/badge/explorer/ThirdPartyBadgeModelInfoPreview.tsx, src/pagePartials/badge/model/CreateCommunityBadgeModel.tsx, src/pagePartials/badge/model/CreateThirdPartyBadgeModel.tsx, src/pagePartials/badge/preview/BadgeView.tsx, src/pagePartials/errors/requiredNotHaveBadge.tsx, src/pagePartials/explorer/badgeModel/index.tsx, src/pagePartials/explorer/badges/index.tsx, src/pagePartials/profile/ManagementProfile.tsx, src/pagePartials/profile/ProfileSelector.tsx, src/pagePartials/profile/created/BadgesCreatedSection.tsx, src/pagePartials/profile/myProfile/ManageBadges.tsx, src/pagePartials/profile/reviewing/BadgesIAmReviewingSection.tsx, src/pagePartials/profile/userInfo/InfoAbout.tsx, src/pagePartials/profile/userInfo/InfoSocial.tsx, src/subgraph/queries/badgeModel.ts, src/subgraph/queries/user.ts
Depends on #373 
- Routes the user from created badge tab to management tab if the user clicks a badge
=> feat: Navigation between created badges tab and management tab

src/hooks/theBadge/useSendClaimNotificationEmail.ts, src/hooks/theBadge/useSendMintNotificationEmail.ts, src/pagePartials/badge/BadgeModelPreview.tsx, src/pagePartials/badge/miniPreview/BadgeMiniPreview.tsx, src/pagePartials/badge/miniPreview/BadgeModelMiniPreview.tsx, src/pagePartials/badge/mint/MintThirdPartyBadgeModel.tsx, src/providers/web3/utils.ts, src/providers/web3/web3ConnectionProvider.tsx
- Fix issue when user changed the network
- Fix sending email to user after mint
=> fix: email send

src/hooks/theBadge/useSendMintNotificationEmail.ts
=> fix: Wrong type on send email

.env.example, src/constants/common.ts, src/utils/relayTx.ts, types/relayedTx.ts
- Add temp staging url for email notifications
=> fix: Fixes prod email

i18n/translations.en.json, src/components/header/Header.tsx, src/components/header/NetworkButton.tsx, src/components/header/UserDropdown.tsx, src/components/utils/WrongNetwork.tsx, src/hooks/useEnsLookup.tsx, src/pagePartials/badge/preview/addons/BadgeNetwork.tsx, src/pagePartials/badge/preview/addons/BadgeTitle.tsx, src/pagePartials/errors/displays/ConnectWalletActionError.tsx, src/pagePartials/errors/displays/ConnectWalletError.tsx, src/pagePartials/errors/displays/NotTheBadgeModelCreatorError.tsx, src/providers/web3/types.ts
Also, add network on badge preview, to know from where is it
=> chore: Add network on header to see where are you connected

src/hooks/subgraph/useBadgeModelMaxAmount.tsx, src/hooks/subgraph/useBadgesUserCanReview.tsx, src/hooks/subgraph/useSubgraph.tsx, src/pagePartials/home/carousels/BadgesInReviewSwiper.tsx, src/pagePartials/profile/statistics/addons/StatisticCard.tsx, src/pagePartials/profile/statistics/addons/styled.tsx, src/pagePartials/profile/statistics/creator/CreatorStatisticContent.tsx, src/pagePartials/profile/statistics/curator/CuratorStatisticContent.tsx, src/pagePartials/profile/statistics/user/UserStatisticContent.tsx, src/providers/web3/types.ts, src/providers/web3/web3ConnectionProvider.tsx
=> fix: statistics display with long strings

i18n/translations.en.json, src/pagePartials/profile/statistics/addons/StatisticCard.tsx, src/pagePartials/profile/statistics/user/UserStatisticContent.tsx
=> feat: Improve some small labels

i18n/translations.en.json, src/pagePartials/badge/mint/steps/StepHeader.tsx, src/pagePartials/badge/mint/steps/StepHeaderThirdParty.tsx, src/pagePartials/badge/model/steps/community/StepHeaderCommunity.tsx
Fixing typos and wording. Finding of beta testing
=> Fixing wording after beta testing

i18n/translations.en.json, src/constants/premiumSubscription.ts, src/hooks/theBadge/useBadgesRequired.ts, src/hooks/useAvailableBackgrounds.tsx, src/pagePartials/badge/preview/generators/BadgeItemGenerator.tsx, src/pagePartials/profile/ManagementProfile.tsx, src/pagePartials/profile/myProfile/ManageSubscription.tsx, src/subgraph/queries/fragments/badge.ts, src/subgraph/queries/user.ts
- Shows your current subscription status
=> feat: Add subscription page

pages/badge/claim/[modelId]/[claimUUID].tsx, src/hooks/theBadge/useIsUserVerified.ts
=> fix: error on validate claim url

src/constants/premiumSubscription.ts, src/pagePartials/badge/preview/BadgeOwnedPreview.tsx, src/pagePartials/profile/myProfile/ManageSubscription.tsx
=> feat: Refactor for supporting multiples tiers badges
